name: Build Android APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Setup Android NDK
      uses: android-actions/setup-android-ndk@v2
      with:
        ndk-version: '25.1.8937393'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.android/build-cache
          $ANDROID_HOME/cache
        key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*') }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: |
        ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease --stacktrace --no-daemon

    - name: Run tests
      run: |
        ./gradlew test --stacktrace --no-daemon
        ./gradlew connectedCheck --stacktrace --no-daemon

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: |
          **/build/outputs/apk/debug/*.apk
          **/build/outputs/apk/androidTest/debug/*.apk
        retention-days: 7

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: |
          **/build/outputs/apk/release/*.apk
        retention-days: 7

    - name: Upload mapping file (if exists)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mapping-files
        path: |
          **/build/outputs/mapping/release/mapping.txt
        retention-days: 30
